[package]
name = "julia-set-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-rs = { git = "https://github.com/arturoc/color-rs.git" }
colorgrad = "0.5.0"
image = "0.24.0"
rayon = "1.5.1"
structopt = "0.3.25"
